### ISSUE TITLE
[TASK] prplmesh recipe for Yocto Poky 2.2 (Morty)

### ISSUE THREAD

**Issue by MuteSpirit** [prplfoundation/meta-prplmesh#1]
Add meta layer with recipes required to build prplMesh with dummy HAL for QEMU machine.

## Detailed description

This task is a fist step of activity to upstreaming prplMesh to RDKB.

Current RDKB uses OE-core 2.2, so recipes will be written following next trend:
Yocto 2.2 -> Yocto 3.1 -> RDKB with OE 2.2 -> RDKB with OE 3.1 (not released yet)

## ToDo

* [x] meta layer sceleton
* [x] bblayers.conf.sample
* [x] local.conf.sample
* [x] prplmesh recipe
* [x] busybox append (to add pgrep)
* [x] kernel bbappend (to add TUN, DUMMY and BRIDGE options)
* [x] image bbappend
* [x] prplmesh packagegroup
* [x] README.md
* [x] Fix warning `WARNING: prplmesh-1.0-r0 do_package_qa: QA Issue: /usr/host/bin/tlvf.py contained in package prplmesh-dev requires /usr/bin/python, but no providers found in RDEPENDS_prplmesh-dev? [file-rdeps]`
* [x] Move comments about RDKB specific scripts/configs into new issues
* [x] Remove RDKB specific scripts/configs from PR
* [x] Open bug in prplMesh about INSTALL_PATH (see [prplMesh #1253](https://github.com/prplfoundation/prplMesh/issues/1253)
* [x] hotfix into prplMesh for `mapfcommon` -> `libmapfcommon` name change
* [x] Recheck need of kernel options added by bbappend
* [x] Fix issues according comments
* [x] Fix license warnings
```
WARNING: core-image-minimal-1.0-r0 do_rootfs: The license listed BSD-2-Clause-Patent was not in the licenses collected for recipe prplmesh
WARNING: core-image-minimal-1.0-r0 do_rootfs: [log_check] core-image-minimal: found 1 warning message in the logfile:
[log_check] WARNING: The license listed BSD-2-Clause-Patent was not in the licenses collected for recipe prplmesh
```
```
WARNING: prplmesh-1.0-r0 do_populate_lic: prplmesh: No generic license file exists for: BSD-2-Clause-Patent in any provider
```

## Exit criteria

* meta layer with allow to build QEMU image with prplmesh inside (with dummy HAL)
* documentation for that
