### ISSUE TITLE
[EPIC] prplMesh on Yocto Poky 3.1

### ISSUE THREAD

**Issue by MuteSpirit** [prplfoundation/meta-prplmesh#16]
## Tasks

* [ ] #8 [TASK] prplmesh.bb: support QEMU in Yocto Poky 3.1
* [ ] [TASK] prplmesh.bb: support RPi 3 in Yocto Poky 3.1
* [ ] [TASK] CI builds for prplMesh in Yocto Poky 3.1
* [ ] #7 [TASK] prplmesh meta layers for Poky/RDKB/project/etc
* [ ] [TASK] Register "meta-prplmesh" on Yocto Project
