### ISSUE TITLE
[TASK] prplmesh.bb: add support BWL  NL80211 for TARGET_PLATFORM "linux"

### ISSUE THREAD

**Issue by MuteSpirit** [prplfoundation/meta-prplmesh#9]
As a developer i'd like to know build prplMesh with BWL_TYPE=NL80211.

To avoid overhead changes related to migration Yocto 3.1 (Dunfell) it's reasonable to add NL80211 support in scope of RDK-B (OE-core 2.2) for RaspberryPi 3 B+

## Exit criteria

Recipes and manuals for build RDK-B (OE-core 2.2) with prplMesh for RPi

## ToDo

* [x] Build QEMU with prplMesh BWL_TYPE=DUMMY in RDK-B environment
* [x] **FAIL** RDK-B for Puma7 CougarMountain
       _(there are Puma meta layers in OpenSource)_
* [x] RDK-B for RPi 3B+ with prplMesh (BWL_TYPE= NL80211)
  * [x] Image is buildable and prplMesh can be run
  * [x] Manually test prplMesh on RPi
  * [x] DEPENDS and RDEPENDS should depend on MSGLIB and other beerocks variables values
  * [x] Publish PR to upstream hotfix for CMake files
  * [x] Publish PR to upstream hotfix for prplmesh_util.sh.in
  * [x] Publish PR to fix issue that `cmake` doesn't use variables passed in command line
  * [x] Publish PR to upstream hotfix about config options for hostapd sockets paths (see #12)
  * [x] ARP monitor feature has been removed [prplMesh PR #1342](https://github.com/prplfoundation/prplMesh/pull/1342/files)
* [x] Add build instructions
* [ ] Reorganize commits

**Comment by MuteSpirit** [comment]
## HOWTO build RDKB based on Yocto 2.2 Morty

Follow [RDKB How To Build](https://wiki.rdkcentral.com/display/RDK/How+to+Build)

```
repo init -u https://code.rdkcentral.com/r/manifests -m rdkb.xml -b rdk/morty-rdkb-20200207
repo sync -j4 --no-clone-bundle
```

**Comment by MuteSpirit** [comment]
# RDKB (OE 3.1) with prplMesh for Raspberry Pi 3B+

## With BWL_TYPE=DUMMY

Image built successfully

## With BWL_TYPE=DWPAL

Not relevant for this board:
* not WAVE Wi-Fi
* no Intel dwpal in OpenSource

## With BWL_TYPE=NL80211

## HOWTO build 

Following [build manual](https://wiki.rdkcentral.com/pages/viewpage.action?pageId=71011616#RDK-B(RaspberryPi3B+)BuildandSetupManual-RouterProfile-BuildInstructions)

```
$ repo init -u https://code.rdkcentral.com/r/manifests -b rdk-next -m rdkb-extsrc.xml
$ repo sync -j4 --no-clone-bundle
```
Fetch meta-prplmesh
```
git clone https://github.com/prplfoundation/meta-prplmesh
```
Add into `conf/bblayers.conf`
```
BBLAYERS =+ "${RDKROOT}/meta-prplmesh"
```
Source build env and run build
```
$ source meta-cmf-raspberrypi/setup-environment (Select option raspberrypi-rdk-broadband.conf)
$ bitbake rdk-generic-broadband-image
```

**Comment by MuteSpirit** [comment]
RDKB (rdkb-next) for Turris Onmia

Following https://github.com/rdkcentral/meta-turris/tree/yocto-dunfell-upgrade

**Comment by MuteSpirit** [comment]
If run build with next configuration
```
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../build/install -H. -B../build -DBWL_TYPE=NL80211 -DTARGET_PLATFORM=linux
make -C ../build/
```
We'll receive compilation error
```
[ 59%] Building CXX object common/beerocks/bwl/CMakeFiles/bwl.dir/shared/netlink_socket.cpp.o
cd /home/mutespirit/inango/prplmesh/prplmesh_root/build/common/beerocks/bwl && /usr/bin/c++  -DBEEROCKS_LINUX -DBEEROCKS_TMP_PATH=\"/tmp/mutespirit/beerocks\" -DCONFIG_CTRL_IFACE -DCONFIG_CTRL_IFACE_UNIX -DELPP_FORCE_USE_STD_THREAD -DELPP_NO_DEFAULT_LOG_FILE -DELPP_SYSLOG -DELPP_THREAD_SAFE -D_FORTIFY_SOURCE=2 -Dbwl_EXPORTS -I/src/utils -I/src/common -I/src/drivers -I/libnl-tiny -I/home/mutespirit/inango/prplmesh/prplmesh_root/prplMesh/common/beerocks/bwl/include -I/home/mutespirit/inango/prplmesh/prplmesh_root/prplMesh/common/beerocks/bcl/include -I/home/mutespirit/inango/prplmesh/prplmesh_root/prplMesh/framework/tlvf/AutoGenerated/include -I/home/mutespirit/inango/prplmesh/prplmesh_root/prplMesh/framework/tlvf/src/include -I/home/mutespirit/inango/prplmesh/prplmesh_root/prplMesh/framework/external/easylogging -I/home/mutespirit/inango/prplmesh/prplmesh_root/build/framework/common/include -I/home/mutespirit/inango/prplmesh/prplmesh_root/prplMesh/framework/common/include -I/home/mutespirit/inango/prplmesh/prplmesh_root/prplMesh/framework/common/zmq/include  -Wall -Wextra -Werror -pthread -Wno-comment -Wno-unused-parameter -Wno-missing-field-initializers -Wno-address-of-packed-member  -std=gnu++11 -O3 -DNDEBUG -O3 -DNDEBUG -s -O2 -Wformat -Wformat-security -Wl,-S -fPIC -fPIE -fstack-protector-strong -fPIC   -fdiagnostics-color=always -std=gnu++11 -o CMakeFiles/bwl.dir/shared/netlink_socket.cpp.o -c /home/mutespirit/inango/prplmesh/prplmesh_root/prplMesh/common/beerocks/bwl/shared/netlink_socket.cpp
/home/mutespirit/inango/prplmesh/prplmesh_root/prplMesh/common/beerocks/bwl/shared/netlink_socket.cpp:11:10: fatal error: netlink/msg.h: No such file or directory
 #include <netlink/msg.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
common/beerocks/bwl/CMakeFiles/bwl.dir/build.make:89: recipe for target 'common/beerocks/bwl/CMakeFiles/bwl.dir/shared/netlink_socket.cpp.o' failed
make[2]: *** [common/beerocks/bwl/CMakeFiles/bwl.dir/shared/netlink_socket.cpp.o] Error 1
make[2]: Leaving directory '/home/mutespirit/inango/prplmesh/prplmesh_root/build'
CMakeFiles/Makefile2:803: recipe for target 'common/beerocks/bwl/CMakeFiles/bwl.dir/all' failed
make[1]: *** [common/beerocks/bwl/CMakeFiles/bwl.dir/all] Error 2
make[1]: Leaving directory '/home/mutespirit/inango/prplmesh/prplmesh_root/build'
Makefile:132: recipe for target 'all' failed
make: *** [all] Error 2
make: Leaving directory '/home/mutespirit/inango/prplmesh/prplmesh_root/build'
```

**Comment by arnout** [comment]
For netlink: we should actually extend cmake/Findnl-3.cmake to also cover nl-tiny - upstream openwrt doesn't have full netlink by default.

For wpa_client: I think it will be easier to just copy wpa_ctrl.c and wpa_ctrl.h in the prplmesh source tree.

**Comment by MuteSpirit** [comment]
One more issue in runtime
```
# /opt/prplmesh/bin/beerocks_controller
# cat /tmp/beerocks/logs/beerocks_controller.log

INFO 14:04:47:984 <1988128816> beerocks_master_main.cpp[284] -->
Running beerocks_controller Version 1.4.0 Build date 2020-05-26_07-19-22


INFO 14:04:47:985 <1988128816> beerocks_version.cpp[116] --> beerocks_controller 1.4.0 (2020-05-26_07-19-22) [d9eb170]
DEBUG 14:04:48:000 <1988128816> network_utils.cpp[935] --> ip_item iface=brlan0
DEBUG 14:04:48:001 <1988128816> network_utils.cpp[935] --> ip_item iface=lo
DEBUG 14:04:48:001 <1988128816> network_utils.cpp[935] --> ip_item iface=br0
DEBUG 14:04:48:001 <1988128816> network_utils.cpp[935] --> ip_item iface=br106
DEBUG 14:04:48:001 <1988128816> network_utils.cpp[935] --> ip_item iface=br403
ERROR 14:04:48:010 <1988128816> network_utils.cpp[614] --> SIOCGIFHWADDR
ERROR 14:04:48:010 <1988128816> beerocks_master_main.cpp[312] --> Failed reading addresses from the bridge!
```

**Comment by MuteSpirit** [comment]
(??) For upstream into prplMesh

[platform_init](https://github.com/prplfoundation/prplMesh/blob/7025ec2a6edcf9cc668501dc15222aca97fb3169/common/beerocks/scripts/prplmesh_utils.sh.in#L35) function in "common/beerocks/scripts/prplmesh_utils.sh.in" uses hardcoded `wlan0`, `wlan2` instead of `BEEROCKS_WLAN1_IFACE` and `BEEROCKS_WLAN2_IFACE` consequently
